import type { FieldSpec } from './types.js';
import {
  TITLE_DOMAIN,
  GENDER_DOMAIN,
  COUNTRY_DOMAIN,
  RESIDENT_DOMAIN,
  CIVIL_STATUS_DOMAIN,
  HOUSE_OWNER_DOMAIN,
  IDENTIFICATION_TYPE_DOMAIN,
  ID_DOC_TYPE_DOMAIN,
  CONTACT_TYPE_DOMAIN,
  ANNUAL_MONTHLY_DOMAIN,
  CURRENCY_DOMAIN,
  OCCUPATION_STATUS_DOMAIN,
  SUBMISSION_TYPE_DOMAIN,
} from './domains.js';

export const HD_SCHEMA: readonly FieldSpec[] = [
  { id: 'HD1', name: 'Record Type', type: 'X', mandatory: 'M', maxLength: 2, fixedValue: 'HD' },
  { id: 'HD2', name: 'Provider Code', type: 'X', mandatory: 'M', maxLength: 8 },
  { id: 'HD3', name: 'File Reference Date', type: 'D', mandatory: 'M', maxLength: 8 },
  { id: 'HD4', name: 'Version', type: 'X', mandatory: 'M', maxLength: 12, fixedValue: '1.0' },
  { id: 'HD5', name: 'Submission Type', type: 'X', mandatory: 'M', maxLength: 1, domain: SUBMISSION_TYPE_DOMAIN },
  { id: 'HD6', name: 'Provider Comments', type: 'X', mandatory: 'NM', maxLength: 100 },
];

export const HD_MIN_FIELDS = 5;
export const HD_MAX_FIELDS = 6;

export const ID_SCHEMA: readonly FieldSpec[] = [
  { id: 'ID1', name: 'Record Type', type: 'X', mandatory: 'M', maxLength: 2, fixedValue: 'ID' },
  { id: 'ID2', name: 'Provider Code', type: 'X', mandatory: 'M', maxLength: 8 },
  { id: 'ID3', name: 'Branch Code', type: 'X', mandatory: 'NM', maxLength: 5 },
  { id: 'ID4', name: 'Subject Reference Date', type: 'D', mandatory: 'M', maxLength: 8 },
  { id: 'ID5', name: 'Provider Subject No', type: 'X', mandatory: 'M', maxLength: 38 },
  { id: 'ID6', name: 'Title', type: 'X', mandatory: 'NM', maxLength: 2, domain: TITLE_DOMAIN },
  { id: 'ID7', name: 'First Name', type: 'X', mandatory: 'M', maxLength: 70 },
  { id: 'ID8', name: 'Last Name', type: 'X', mandatory: 'M', maxLength: 70 },
  { id: 'ID9', name: 'Middle Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID10', name: 'Suffix', type: 'X', mandatory: 'NM', maxLength: 40 },
  { id: 'ID11', name: 'Nickname', type: 'X', mandatory: 'NM', maxLength: 40 },
  { id: 'ID12', name: 'Previous Last Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID13', name: 'Gender', type: 'X', mandatory: 'M', maxLength: 1, domain: GENDER_DOMAIN },
  { id: 'ID14', name: 'Date of Birth', type: 'D', mandatory: 'M', maxLength: 8 },
  { id: 'ID15', name: 'Place of Birth', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID16', name: 'Country of Birth', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID17', name: 'Nationality', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID18', name: 'Resident', type: 'X', mandatory: 'NM', maxLength: 1, domain: RESIDENT_DOMAIN },
  { id: 'ID19', name: 'Civil Status', type: 'X', mandatory: 'NM', maxLength: 1, domain: CIVIL_STATUS_DOMAIN },
  { id: 'ID20', name: 'Number of Dependants', type: 'N', mandatory: 'NM', maxLength: 2 },
  { id: 'ID21', name: 'Cars Owned', type: 'N', mandatory: 'NM', maxLength: 3 },
  { id: 'ID22', name: 'Spouse First Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID23', name: 'Spouse Last Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID24', name: 'Spouse Middle Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID25', name: '(Future Use)', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID26', name: 'Mother Maiden Full Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID27', name: '(Future Use)', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID28', name: 'Father First Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID29', name: 'Father Last Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID30', name: 'Father Middle Name', type: 'X', mandatory: 'NM', maxLength: 70 },
  { id: 'ID31', name: 'Father Suffix', type: 'X', mandatory: 'NM', maxLength: 40 },
  { id: 'ID32', name: 'Address 1: Address Type', type: 'X', mandatory: 'M', maxLength: 2, fixedValue: 'MI' },
  { id: 'ID33', name: 'Address 1: FullAddress', type: 'X', mandatory: 'D', maxLength: 400 },
  { id: 'ID34', name: 'Address 1: StreetNo', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID35', name: 'Address 1: PostalCode', type: 'X', mandatory: 'NM', maxLength: 4 },
  { id: 'ID36', name: 'Address 1: Subdivision', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID37', name: 'Address 1: Barangay', type: 'X', mandatory: 'NM', maxLength: 60 },
  { id: 'ID38', name: 'Address 1: City', type: 'X', mandatory: 'D', maxLength: 50 },
  { id: 'ID39', name: 'Address 1: Province', type: 'X', mandatory: 'D', maxLength: 50 },
  { id: 'ID40', name: 'Address 1: Country', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID41', name: 'Address 1: House Owner/Lessee', type: 'X', mandatory: 'NM', maxLength: 1, domain: HOUSE_OWNER_DOMAIN },
  { id: 'ID42', name: 'Address 1: Occupied Since', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID43', name: 'Address 2: Address Type', type: 'X', mandatory: 'D', maxLength: 2, fixedValue: 'AI' },
  { id: 'ID44', name: 'Address 2: FullAddress', type: 'X', mandatory: 'D', maxLength: 400 },
  { id: 'ID45', name: 'Address 2: StreetNo', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID46', name: 'Address 2: PostalCode', type: 'X', mandatory: 'NM', maxLength: 4 },
  { id: 'ID47', name: 'Address 2: Subdivision', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID48', name: 'Address 2: Barangay', type: 'X', mandatory: 'NM', maxLength: 60 },
  { id: 'ID49', name: 'Address 2: City', type: 'X', mandatory: 'D', maxLength: 50 },
  { id: 'ID50', name: 'Address 2: Province', type: 'X', mandatory: 'D', maxLength: 50 },
  { id: 'ID51', name: 'Address 2: Country', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID52', name: 'Address 2: House Owner/Lessee', type: 'X', mandatory: 'NM', maxLength: 1, domain: HOUSE_OWNER_DOMAIN },
  { id: 'ID53', name: 'Address 2: Occupied Since', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID54', name: 'Identification 1: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: IDENTIFICATION_TYPE_DOMAIN },
  { id: 'ID55', name: 'Identification 1: Number', type: 'X', mandatory: 'D', maxLength: 20 },
  { id: 'ID56', name: 'Identification 2: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: IDENTIFICATION_TYPE_DOMAIN },
  { id: 'ID57', name: 'Identification 2: Number', type: 'X', mandatory: 'D', maxLength: 20 },
  { id: 'ID58', name: 'Identification 3: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: IDENTIFICATION_TYPE_DOMAIN },
  { id: 'ID59', name: 'Identification 3: Number', type: 'X', mandatory: 'D', maxLength: 20 },
  { id: 'ID60', name: 'ID 1: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: ID_DOC_TYPE_DOMAIN },
  { id: 'ID61', name: 'ID 1: Number', type: 'X', mandatory: 'D', maxLength: 40 },
  { id: 'ID62', name: 'ID 1: IssueDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID63', name: 'ID 1: IssueCountry', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID64', name: 'ID 1: ExpiryDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID65', name: 'ID 1: Issued By', type: 'X', mandatory: 'NM', maxLength: 250 },
  { id: 'ID66', name: 'ID 2: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: ID_DOC_TYPE_DOMAIN },
  { id: 'ID67', name: 'ID 2: Number', type: 'X', mandatory: 'D', maxLength: 40 },
  { id: 'ID68', name: 'ID 2: IssueDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID69', name: 'ID 2: IssueCountry', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID70', name: 'ID 2: ExpiryDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID71', name: 'ID 2: Issued By', type: 'X', mandatory: 'NM', maxLength: 250 },
  { id: 'ID72', name: 'ID 3: Type', type: 'X', mandatory: 'D', maxLength: 2, domain: ID_DOC_TYPE_DOMAIN },
  { id: 'ID73', name: 'ID 3: Number', type: 'X', mandatory: 'D', maxLength: 40 },
  { id: 'ID74', name: 'ID 3: IssueDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID75', name: 'ID 3: IssueCountry', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID76', name: 'ID 3: ExpiryDate', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID77', name: 'ID 3: Issued By', type: 'X', mandatory: 'NM', maxLength: 250 },
  { id: 'ID78', name: 'Contact 1: Type', type: 'X', mandatory: 'D', maxLength: 1, domain: CONTACT_TYPE_DOMAIN },
  { id: 'ID79', name: 'Contact 1: Value', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID80', name: 'Contact 2: Type', type: 'X', mandatory: 'D', maxLength: 1, domain: CONTACT_TYPE_DOMAIN },
  { id: 'ID81', name: 'Contact 2: Value', type: 'X', mandatory: 'D', maxLength: 100 },
  { id: 'ID82', name: 'Employment: Trade Name', type: 'X', mandatory: 'NM', maxLength: 120 },
  { id: 'ID83', name: 'Employment: TIN', type: 'X', mandatory: 'NM', maxLength: 20 },
  { id: 'ID84', name: 'Employment: Phone Number', type: 'X', mandatory: 'NM', maxLength: 20 },
  { id: 'ID85', name: 'Employment: PSIC', type: 'X', mandatory: 'NM', maxLength: 5 },
  { id: 'ID86', name: 'Employment: GrossIncome', type: 'N', mandatory: 'NM', maxLength: 15 },
  { id: 'ID87', name: 'Employment: Annual/Monthly', type: 'X', mandatory: 'NM', maxLength: 1, domain: ANNUAL_MONTHLY_DOMAIN },
  { id: 'ID88', name: 'Employment: Currency', type: 'X', mandatory: 'NM', maxLength: 3, domain: CURRENCY_DOMAIN },
  { id: 'ID89', name: 'Employment: OccupationStatus', type: 'X', mandatory: 'NM', maxLength: 1, domain: OCCUPATION_STATUS_DOMAIN },
  { id: 'ID90', name: 'Employment: DateHiredFrom', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID91', name: 'Employment: DateHiredTo', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID92', name: 'Employment: Occupation', type: 'X', mandatory: 'NM', maxLength: 4 },
  { id: 'ID93', name: 'Sole Trader: Trade Name', type: 'X', mandatory: 'NM', maxLength: 120 },
  { id: 'ID94', name: 'Sole Trader Address 1: Address Type', type: 'X', mandatory: 'NM', maxLength: 2 },
  { id: 'ID95', name: 'Sole Trader Address 1: FullAddress', type: 'X', mandatory: 'NM', maxLength: 400 },
  { id: 'ID96', name: 'Sole Trader Address 1: StreetNo', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID97', name: 'Sole Trader Address 1: PostalCode', type: 'X', mandatory: 'NM', maxLength: 4 },
  { id: 'ID98', name: 'Sole Trader Address 1: Subdivision', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID99', name: 'Sole Trader Address 1: Barangay', type: 'X', mandatory: 'NM', maxLength: 60 },
  { id: 'ID100', name: 'Sole Trader Address 1: City', type: 'X', mandatory: 'NM', maxLength: 50 },
  { id: 'ID101', name: 'Sole Trader Address 1: Province', type: 'X', mandatory: 'NM', maxLength: 50 },
  { id: 'ID102', name: 'Sole Trader Address 1: Country', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID103', name: 'Sole Trader Address 1: House Owner/Lessee', type: 'X', mandatory: 'NM', maxLength: 1, domain: HOUSE_OWNER_DOMAIN },
  { id: 'ID104', name: 'Sole Trader Address 1: Occupied Since', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID105', name: 'Sole Trader Address 2: Address Type', type: 'X', mandatory: 'NM', maxLength: 2 },
  { id: 'ID106', name: 'Sole Trader Address 2: FullAddress', type: 'X', mandatory: 'NM', maxLength: 400 },
  { id: 'ID107', name: 'Sole Trader Address 2: StreetNo', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID108', name: 'Sole Trader Address 2: PostalCode', type: 'X', mandatory: 'NM', maxLength: 4 },
  { id: 'ID109', name: 'Sole Trader Address 2: Subdivision', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID110', name: 'Sole Trader Address 2: Barangay', type: 'X', mandatory: 'NM', maxLength: 60 },
  { id: 'ID111', name: 'Sole Trader Address 2: City', type: 'X', mandatory: 'NM', maxLength: 50 },
  { id: 'ID112', name: 'Sole Trader Address 2: Province', type: 'X', mandatory: 'NM', maxLength: 50 },
  { id: 'ID113', name: 'Sole Trader Address 2: Country', type: 'X', mandatory: 'NM', maxLength: 2, domain: COUNTRY_DOMAIN },
  { id: 'ID114', name: 'Sole Trader Address 2: House Owner/Lessee', type: 'X', mandatory: 'NM', maxLength: 1, domain: HOUSE_OWNER_DOMAIN },
  { id: 'ID115', name: 'Sole Trader Address 2: Occupied Since', type: 'D', mandatory: 'NM', maxLength: 8 },
  { id: 'ID116', name: 'Sole Trader Identification 1: Type', type: 'X', mandatory: 'NM', maxLength: 2, domain: IDENTIFICATION_TYPE_DOMAIN },
  { id: 'ID117', name: 'Sole Trader Identification 1: Number', type: 'X', mandatory: 'NM', maxLength: 20 },
  { id: 'ID118', name: 'Sole Trader Identification 2: Type', type: 'X', mandatory: 'NM', maxLength: 2, domain: IDENTIFICATION_TYPE_DOMAIN },
  { id: 'ID119', name: 'Sole Trader Identification 2: Number', type: 'X', mandatory: 'NM', maxLength: 20 },
  { id: 'ID120', name: 'Sole Trader Contact 1: Type', type: 'X', mandatory: 'NM', maxLength: 1, domain: CONTACT_TYPE_DOMAIN },
  { id: 'ID121', name: 'Sole Trader Contact 1: Value', type: 'X', mandatory: 'NM', maxLength: 100 },
  { id: 'ID122', name: 'Sole Trader Contact 2: Type', type: 'X', mandatory: 'NM', maxLength: 1, domain: CONTACT_TYPE_DOMAIN },
  { id: 'ID123', name: 'Sole Trader Contact 2: Value', type: 'X', mandatory: 'NM', maxLength: 100 },
];

export const ID_MIN_FIELDS = 122;
export const ID_MAX_FIELDS = 123;
